name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: tar.gz

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build release
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create archive (Unix)
      if: matrix.archive == 'tar.gz'
      run: |
        mkdir -p release/instryx-${{ github.ref_name }}-${{ matrix.target }}
        cp target/${{ matrix.target }}/release/instryx release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        cp README.md LICENSE CHANGELOG.md release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        cp -r examples release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        tar -czf instryx-${{ github.ref_name }}-${{ matrix.target }}.tar.gz -C release instryx-${{ github.ref_name }}-${{ matrix.target }}

    - name: Create archive (Windows)
      if: matrix.archive == 'zip'
      run: |
        mkdir -p release/instryx-${{ github.ref_name }}-${{ matrix.target }}
        cp target/${{ matrix.target }}/release/instryx.exe release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        cp README.md LICENSE CHANGELOG.md release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        cp -r examples release/instryx-${{ github.ref_name }}-${{ matrix.target }}/
        Compress-Archive -Path release/instryx-${{ github.ref_name }}-${{ matrix.target }} -DestinationPath instryx-${{ github.ref_name }}-${{ matrix.target }}.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: instryx-${{ github.ref_name }}-${{ matrix.target }}
        path: instryx-${{ github.ref_name }}-${{ matrix.target }}.*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/instryx-*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}